### ISSUE TITLE
OAuth2 - /oauth2/access-token endpoint errors

### ISSUE THREAD

**Issue by hudecsamuel** [mergado/mergado-apps#10]
Currently requests on this endpoint that result in some error returns redirect to Accounts login page (And 200 status code).

![screenshot from 2016-04-13 09 35 40](https://cloud.githubusercontent.com/assets/13395909/14486042/2a0882fc-015b-11e6-9d60-6c4f99247ec9.png)

I believe this is due user permission checking ($presenter->user), and on POST request without Mergado frontend session this results in redirect to accounts (as if you are not logged in). This is not realy ideal for server side POST request error.

Idealy errors would result in specific http status code and JSON message (with some info about the error).

**Comment by smuuf** [comment]
Looks like this issue is already resolved. OAuth error messages are properly returned in JSON on `/token` endpoint - without forcing "user" to log in.
