### ISSUE TITLE
API - filtrování statistik

### ISSUE THREAD

**Issue by kluvi** [mergado/mergado-apps#102]
This is **a feature request**

---

### Expected behaviour
Hodilo by se filtrování statistik podle toho, jaká data jsou k dispozici. Tj například když si potřebuju vypsat statistiky všech produktů, které mají nějaká data například ze statistik na zboží.cz. Zvlášť u toho zbozi.cz je to důležité, protože statistiky se negenerují pro všechny produkty. Takže když udělám request na endpoint `/projects/XXX/stats/products`, musím projít několik stránek produktů, které žádná data nemají (resp. nemají data která chci) než narazím na nějaký produkt co je má.
Mělo by to pak mít i vliv na vrácený celkový počet záznamů - viz #97 (tj budu schopný zjistit kolik produktů má pro daný den stažené statistiky ze zdroje xxx)

**Comment by ondrejbenes** [comment]
Jak by sis představoval syntaxi toho "query language"?
Endpointy pro statistiky produktů už umí filtrovat podle `item_id` pomocí `filter_by` argu. Takže bychom třeba do `filter_by` přidali něco ve stylu `zbozi_id`:`_exists_`? Request by mohl vypadat třeba:

```
/shops/2/stats/products?filter_by={'zbozi_id':'_exists_'}
```

**Comment by kluvi** [comment]
Ano, souhlasím s přidáním do filter_by.. Ale lepší mě přijde ve stylu `from_source: heureka-sortiment` (tj "produkt, který má jakákoliv data pocházející ze zdroje heureka-sortiment"). Protože kdyby tam bylo to `_exists_`, tak by bylo na zodpovědnosti vývojáře, aby věděl odkud která data pochází.
Ale zároveň s tím uvítám klidně i ten `_exists_`.. ten se ale aktuálně hodí spíš na ruční kontrolu než na běžné stahování statistik.
