### ISSUE TITLE
API - Queries - Creating query with existing name results in 500 error

### ISSUE THREAD

**Issue by hudecsamuel** [mergado/mergado-apps#11]
So today I accidentaly stumbled on 500 error while I was trying to replicate query with regular expression that i created in mergado UI (not the interesting part)

Here is how it looks if i get it from api:
![screenshot from 2016-04-14 10 42 47](https://cloud.githubusercontent.com/assets/13395909/14522280/0e872fb4-022e-11e6-8031-9ac7e515ccb3.png)

 I accidentaly tried to create rule with the same name (the detection is apparently case insensitive), and that resulted in 500 Internal server error:
![screenshot from 2016-04-14 10 35 34](https://cloud.githubusercontent.com/assets/13395909/14522354/7173ab5c-022e-11e6-8700-3c000f680652.png)

This should be 409 Conflict error if I'm correct.

**Comment by paveldedik** [comment]
Yes, you are right, this request should result in 409 Conflict. It will be fixed in release 0.1.2.
