### ISSUE TITLE
Appcloud - Redis

### ISSUE THREAD

**Issue by hudecsamuel** [mergado/mergado-apps#15]
Hello.

There are multiple use cases where it would be realy great to have Redis for applications on Appcloud. Up to now it wasn't that much of a problem, but it would help nonetheless, but now we want to do stuff with Mergado statistics and new rules (defined by application) and Redis would help with caching.

What do you think about it?

**Comment by smuuf** [comment]
Giving apps access to *their own* Redis storage is a great idea.

Although having multi-tenant Redis database accessible to separate apps and securing such architecture is something *we (would) have to investigate first* and then come up with some ideas of how to implement it in App Cloud, where apps are being hosted.

And that is something that can and will take some time.

**Comment by hudecsamuel** [comment]
This is already implemented, thanks.
