### ISSUE TITLE
MessageApi.js as npm package

### ISSUE THREAD

**Issue by hudecsamuel** [mergado/mergado-apps#18]
It would be cool to have MessageApi.js availible as [npm](https://www.npmjs.com/) package.
It would mostly be nice when i am using module bundling system like [Webpack](https://webpack.github.io/)
I might look into it and try to suggest concrete implementation 

**this is just a suggestion:** *Make it open source and write documentation on how to operate with Mergado iframe messages (What messages we can do etc)*

**Comment by smuuf** [comment]
IIRC having *MessageApi* as npm would probably mean that it would need a separate standalone *git* repository. *MessageApi.js* is designed to be included from our own site, which avoids potential troubles with updating when a new version is released.

What would be the point (benefits) of having it as separate package?

**Comment by hudecsamuel** [comment]
The main benefit would be interoperability with other npm packages. 
Right now I am doing something like:
```javascript
const Mergado = window['Mergado'];

Mergado.tellHeight()
```

or for short
```javascript
window['Mergado'].tellHeight();
```

I do not consider this a major issue, it would just be nice imho to use the API just like any other npm package:
```javascript
import Mergado from 'mergado-message-api';

Mergado.tellHeight();
```

but the updating issue might arise eventualy , if you plan to break backward compatibility :smile:

**Comment by smuuf** [comment]
Still, packaging Message API into your own application would create a possibility of breaking when something needs to be changed on either side - Mergado or the app.

Having a single point from where apps should obtain Message API solves this.

I'm closing this issue for now. If there is any problem in the future, we can always reopen.
