### ISSUE TITLE
Notifications - duplicate values in channels

### ISSUE THREAD

**Issue by hudecsamuel** [mergado/mergado-apps#19]
When I write a notification the returned json looks like this, with multiple duplicate entries in channels array. 
Four users have access to that eshop, so there might be some correlation  *(magic)* , but i didn't investigate that further 
```json
{
  "body": "Your eshop is total screwed. (This is in official documentation in Apiary :D) ",
  "channels": [
    "frontend", 
    "frontend", 
    "frontend", 
    "frontend" 
  ],
  "title": "eshop fuckup",
  "created_at": "2016-09-05 14:49:07",
  "priority": "medium",
  "scope": "eshop",
  "id": "80551"
}
```

And secondarily that example in Apiary documentation might be worth changing (body and title) :smile:

**Comment by paveldedik** [comment]
Fixed.
