### ISSUE TITLE
Appcloud - Supervisor

### ISSUE THREAD

**Issue by hudecsamuel** [mergado/mergado-apps#20]
It would be nice to have [Supervisor](http://supervisord.org/) for each app on Appcloud.
I wanted to run several tasks as Jobs in [Queue](https://laravel.com/docs/5.2/queues#supervisor-configuration) , which requires worker to run at all times. 

I tried to work aroud it with this code (would run once in an hour, with current cron set on BiddingFox)

``` php
//checks if there is already running process coresponding to laravel queue worker
exec('ps -aux | grep "[p]hp ' . base_path('artisan') . ' queue:work --daemon --tries=3"', $output);
//starts one if there is not
if(empty($output)) {
    $process = new Process("php ". base_path('artisan') . " queue:work --daemon --tries=3");
    $process->start();
}
```

only to find out that `exec()` is disabled on Appcloud as a safety feature (as it probably should be)

So Supervisor would help a lot, in cases where I dont want to delay request (rule processing for example) with calculations that can be done after its finished
#15 Redis would help also as it is  beter driver for this than relational database

**Comment by smuuf** [comment]
This is something App Cloud is *totally* not prepared for, yet.

**Comment by hudecsamuel** [comment]
Yea I figured that out. but still wanted to talk about it.

And i think i found a workaroud that works.
