### ISSUE TITLE
Notifications - notify specific user

### ISSUE THREAD

**Issue by hudecsamuel** [mergado/mergado-apps#21]
Currently there is no way to send Mergado notification to specific user (beside the `owner`), which would be realy nice mainly for applications of `user` type.

The only API endpoint for sending notification is:
 `POST` `https://app.mergado.com/api/shops/id/notifications/`

There is also endpoint for getting user notifications:
`GET` `https://app.mergado.com/api/users/id/notifications/`

 but not one for sending him one.

Logicaly that should be:
`POST` `https://app.mergado.com/api/users/id/notifications/`

**Comment by paveldedik** [comment]
We have added an endpoint for notifying specific users: http://docs.mergado.apiary.io/#reference/core/notifications/notify-a-user
