### ISSUE TITLE
API - Notifications - "scope": "shop"  results in 400 Bad Request

### ISSUE THREAD

**Issue by hudecsamuel** [mergado/mergado-apps#22]
[API endpoint](http://docs.mergado.apiary.io/#reference/core/notifications/notify-eshop-members) for creating notification for `shop` should have two options for it's `scope` attribute: `owner` and `shop` (according to apiary it defaults to `shop`).

I found out that it defaults to `owner` and when i tried to set it to `shop` by sending this json:

```json
{
  "title": "Test notification",
  "body": "This is a test.",
  "channels": [
    "frontend"
  ],
  "created_at": "2016-10-04 11:43:18",
  "priority": "high",
  "scope": "shop"
}
```

 it returned response wit status code 400 and this message:
```json
{
  "message": {
    "scope": "Field 'scope' is not in required format."
  }
}
```

Screenshot from Postman:
![screenshot from 2016-10-04 11 49 38](https://cloud.githubusercontent.com/assets/13395909/19069901/31d71078-8a29-11e6-8c65-3b6cc57051d6.png)

**Comment by paveldedik** [comment]
I believe this was fixed in v0.2.4 (http://mergado.github.io/docs/changelog/).

Thanks for reporting the issue.
