### ISSUE TITLE
How to work with tokens?

### ISSUE THREAD

**Issue by michalwiglasz** [mergado/mergado-apps#23]
What is the expected way of dealing with tokens?

1) App should request new token every time
This is very simple approach, but leads to very large number of active tokens (e.g. if app generates one request per minute, there could be up to 60 valid tokens at the same time)

2) App should store the tokens somewhere and request new ones only after expiration
This would require some persistent token storage in the app and reduces number of valid tokens and OAuth requests.

If **2** is the way to go, it would be nice, if the api returned token expiration as an datetime value instead of relative number of seconds, because the app time can be different from the API server time (oauth permits up to 5 min difference, as far as I remember). This could lead to situation, where the app thinks it owns a valid token, but the api thinks it already expired. Properly written app should be able to handle this, though.

**Comment by smuuf** [comment]
You are right, the second way is the way it is.

The server returns the `expires_in` field as the relative number of seconds in which the access token will expire - as the [OAuth2 RFC](https://tools.ietf.org/html/rfc6749#page-35) specifies *(recommends)*.

Using this `expires_in` figure the client can determine the final expiration datetime by itself, using its own time settings, **avoiding** any problems with possible time differences between our server and the client (including potentially different timezones, or whatever).

Ultimately, the app has to be able to handle situations where it is trying to use an access token, which the app thinks is valid, but the server decides that it is expired. The time is not the only factor there; access tokens can be, for example, just revoked by the user disabling the app in Mergado.

As https://github.com/jricher puts it:

> As a client, you can have an idea of when the token will expire, but generally speaking the client just uses the token to see if it works. This is because the token could have been revoked for any number of reasons beyond expiration -- user decides to revoke it explicitly, authorization server decides to throw out all live tokens for a client, client gets deprovisioned, it's tuesday and the system feels like it, etc. In all of these cases, the client will have no idea whether or not something happened until it tries to use the token and fails.

~https://www.quora.com/Is-it-possible-to-know-when-an-OAuth2-token-expires
