### ISSUE TITLE
MAIA: Uncaught TypeError: Cannot read property 'style' of null

### ISSUE THREAD

**Issue by michalwiglasz** [mergado/mergado-apps#24]
In function `iframeLoad(appFrame)`

``` javascript
switch (msgType) {
                case 'height':
/* HERE -- */
                    el.style.height = parseInt(msg.data.ht) + "px";
/* HERE -^ */
                    break;
```

Happens every time the iframe is reloaded (or its url changes after clicking link).

**Comment by smuuf** [comment]
This is caused *(or at least I can reproduce it)* by calling `.tellHeight()` ***before*** Message API has time to initialize itself.

The solution is to wait until the `Mergado` object is initialized *(it's communication with parent `iframe` is established)* and then make calls.

Moreso, starting from next release `Mergado` object will have a new `Mergado.onLoad` callback property which can be set by the app developer and which will be fired after the connection with parent `iframe` was properly established. Example:

```js
window.onload = function(){
	Mergado.onLoad = function(m) {
		m.tellHeight(4000);
	}
}
```
