### ISSUE TITLE
OAuth access scopes settings seems to have no effect

### ISSUE THREAD

**Issue by michalwiglasz** [mergado/mergado-apps#25]
My app ("BR") has currently set no access rights. However, it is able to fetch list of project queries and also search them and iterate over products.

Another issue is, that regardless of scope settings, my app is unable to fetch product stats:

```
The server could not verify that you are authorized to access the URL requested.  You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required. [https://app.mergado.com/api/projects/13357/stats/products]
```

**Comment by michalwiglasz** [comment]
(I assume i need `project.stats.read`, I tried also `eshop.stats.read` with the same result)

**Comment by smuuf** [comment]
Is it possible that you are trying to use wrong *client ID* to obtain *access tokens* for your app?

In any way we don't see neither of the  `project.stats.read` nor `eshop.stats.read` scopes being set for your "BR" app. Try adding them in your app's [administration](https://app.mergado.com/developers/).

**Comment by michalwiglasz** [comment]
Přemku, já nejsem až tak blbej :)

...

Teda to jsem chtěl napsat původně. Když jsem přesouval kód z pricingr do BR, nezměnil jsem v konfiguraci Client ID. Až když jste pricingr dnes smazali, tak to vyšlo najevo.
