### ISSUE TITLE
API: Nonexistent `app_rule_type` returns 500 Internal server error

### ISSUE THREAD

**Issue by hudecsamuel** [mergado/mergado-apps#28]
While trying out new application rules I stumbled across 500 in API (I forgot `.dev` at first). When trying to create new rule with `"type": "app"` I misstyped the `"app_rule_type"` attribute in `"data"` and it returns `500 Internal Server Error` instead of corrent status code and hopefuly human readable message.

[Endpoint](http://docs.mergado.apiary.io/#reference/core/rules/create-a-rule)
Request json body:
```json
{
	"name": "FIE - test app rule",
	"type": "app",
	"project_element_id": null,
	"applies": true,
	"priority": 200,
	"is_deletable": true,
	"is_movable": false,
	"is_editable": false,
	"is_pausable": false,
	"data": {
		"app_rule_type": "apps.feedimageeditor.example.nonexistent"
	},
	"queries": []
}
```

Response:
```json
{
  "message": "Internal Server Error"
}
```

With correct type everything seems to work fine, but it took me a while to figure out what was the problem.

**Comment by paveldedik** [comment]
This was fixed in API v0.3.0
