### ISSUE TITLE
API - Rules - creating rules results in 400

### ISSUE THREAD

**Issue by hudecsamuel** [mergado/mergado-apps#3]
So today I tried to create a rule with ``"project_element_id": null`` as I know there are such rules (bidding as example)

Example bidding rule created in Mergado GUI:
![screenshot from 2016-04-13 08 11 52](https://cloud.githubusercontent.com/assets/13395909/14484580/c5b7462a-0151-11e6-912b-6ed746df6e66.png)

Creating bidding rule with ``"project_element_id": null``  resulted in 400 (I'm pretty sure it worked, maybe even yesterday. So this must be the result of recent "fix" :smile: )
![screenshot from 2016-04-13 08 13 46](https://cloud.githubusercontent.com/assets/13395909/14484510/50e00c2e-0151-11e6-8efd-0104c680ab80.png)

So then I proceed and and tried out creating it with the correct ``MAX_CPC`` ``project_element_id``, wich suprisingly resulted in the same 400 error. even though the element id is correct
![screenshot from 2016-04-13 08 14 10](https://cloud.githubusercontent.com/assets/13395909/14484511/51a9730c-0151-11e6-9599-5599f9da3276.png)

Checked if the element is realy there: 
![screenshot from 2016-04-13 08 33 37](https://cloud.githubusercontent.com/assets/13395909/14484719/94201fc8-0152-11e6-83ca-03c6616c431a.png)

The problem is not ``rule_type`` specific, tried calc rule too:
![screenshot from 2016-04-13 08 41 00](https://cloud.githubusercontent.com/assets/13395909/14484853/82880806-0153-11e6-82c3-e2538c9c17f5.png)

ping @paveldedik

**Comment by paveldedik** [comment]
It should be fixed now.

BTW It'd be probably better if you copied the request/responce in JSON instead of making a screanshot (which I cannot copy&paste).
