### ISSUE TITLE
<a href target=_blank> does nothing

### ISSUE THREAD

**Issue by michalwiglasz** [mergado/mergado-apps#30]
For example:
``` html
<a href="https://google.com" target="_blank">Google</a>
```

does not work, nothing happens after clicking. If target is set to `_top`, error occurs:

Unsafe JavaScript attempt to initiate navigation for frame with URL 'https://app.mergado.com/eshops/950/applications/view/?app=myapp&projectId=1' from frame with URL 'https://appcloud.mergado.com/apps/myapp/eshop/1/project/1367'. The frame attempting navigation of the top-level window is sandboxed, but the 'allow-top-navigation' flag is not set.

**Comment by hudecsamuel** [comment]
[Look here](http://mergado.github.io/docs/apps/iframe-api.html)  for documentation on Message API.

For opening link in new tab you can use `Mergado.openWindow(string url)`

Example:
```html
<a onclick="Mergado.openWindow('https://google.com')" >Google</a>
```

**Comment by michalwiglasz** [comment]
Damn, why so complicated? Turned out THIS can fix everything in the blink of an eye:

```javascript
$(function() {
    $('a[target=_blank]').click(function(event) {
        event.preventDefault();
        Mergado.openWindow($(this).attr('href'));
    });
});
```

If somebody (@smuuf) makes this part of `MessageApi.js`, I'll buy him a chocolate bar. It would be cool to just add
```
Mergado.fixLinks();
```

to my JS.

**Comment by michalwiglasz** [comment]
Jo a už vím, co jsme chtěli na Přemka: k čemu je `Mergado.startDownload`, když mi to funguje i bez toho, stačí poslat správný `content-type` a `content-disposition`. Chrome, FF a IE je OK.

**Comment by smuuf** [comment]
IIRC the `startDownload` method was supposed to solve problems with initiating a download from inside the `iframe ` in the very Firefox. I believe @hudecsamuel could hopefully recall a little bit more - why this was needed to be solved.

*(so are you telling me that it is no longer needed?)*

**Comment by michalwiglasz** [comment]
> (so are you telling me that it is no longer needed?)

I'm not using it, seems fine from my POV. But there can be issues I cannot see now.

**Comment by hudecsamuel** [comment]
> Mergado.fixLinks();

Calling `Mergado.fixLinks()` on each page change as proposed seems more complicated imho, but whatever.

> Maybe @hudecsamuel could hopefully recall a little bit more - why this was needed to be solved.

I can't recall the exact problem, but I remember we were dealing with downloading `CSV` and it ran perfectly in Chrome, but since Firefox is a bit more restrictive about sandboxed iframes it wasn't working as seemlesly there.

**Comment by michalwiglasz** [comment]
> Calling Mergado.fixLinks() on each page change as proposed seems more complicated imho, but whatever.

Complicated than what? Than adding 5 lines of jquery? Or easier than need to remember to use onclick instead of href for each external link? Doesn't seem so to me.

(And if a new problem with hyperlinks arises, it can be fixed just by updating Mergado.js without touching apps.)

> I can't recall the exact problem, but I remember we were dealing with downloading CSV and it ran perfectly in Chrome, but since Firefox is a bit more restrictive about sandboxed iframes it wasn't working as seemlesly there.

CSV seems to work fine even in (newest) Firefox.

**Comment by hudecsamuel** [comment]
> Complicated than what? Than adding 5 lines of jquery? Or easier than need to remember to use onclick instead of href for each external link? Doesn't seem so to me.

Depends on the technology stack you are using, and I was comparing to onclick handlers.
But I think we should agree to disagree on this matter.

Btw adding that proposed 5 lines of jQuery to your code isn't that hard and it wouldn't pollute the MessageApi.js. (which is not depenedent on jQuery at all)

**Comment by michalwiglasz** [comment]
I didn't say it should be copy@pasted into Mergado JS and polluted by jQuery. Of course integration should be framework-free in order not to break user's JS stack.


I'm old school, I don't like JS-only hyperlinks :) Back in my days it was considered unprofessional.


Od: Samuel Hudec <notifications@github.com>

Odesláno: 14. listopadu 2016 9:47
Komu: mergado/mergado-apps
Kopie: Michal Wiglasz; Author
Předmět: Re: [mergado/mergado-apps] <a href target=_blank> does nothing (#30)


Complicated than what? Than adding 5 lines of jquery? Or easier than need to remember to use onclick instead of href for each external link? Doesn't seem so to me.

Depends on the technology stack you are using, and I was comparing to onclick handlers.
But I think we should agree to disagree on this matter.

Btw adding that proposed 5 lines of jQuery to your code isn't that hard and it wouldn't pollute the MessageApi.js. (which is not depenedent on jQuery at all)

-

**Comment by michalwiglasz** [comment]
btw:

> Tak trochu mimo to finišování s aplikací posílám dotaz k funkci stažení do CSV v prohlížeči Firefox. Byl tu Michal Janík, že mu to ve Firefoxu nejde (po kliknutí se nezačne stahovat CSV soubor).

takže to asi je třeba

**Comment by smuuf** [comment]
Closing this. It's better to left any possible implementation of some `Mergado.fixLinks()` method to the developer himself, since we don't want to pollute `Mergado` object with this "level" of magic methods.
