### ISSUE TITLE
Developers - Creating app rule types

### ISSUE THREAD

**Issue by hudecsamuel** [mergado/mergado-apps#31]
Creating new type of application rule seems easy: just hit the little `plus` in `rules section` in apps page in developers, fill in the form and hit `create`. 

The rule is created! Nice!

Well not so fast. to which stage this new rule type belongs? **I don't know.**
Oh ok so maybe it would work with both stages. (little hint: **No**) 
Lets create another one with url pointing to production app this time: Went through the creation process again. Clicked `Create`
**The rule from before is overwritten by the new one.** *(Still have no idea which stage it belongs to at this time)*

My thought: ***This is bullshit!*** 

So how am I supposed to create multiple application rule types? *(Don't say i won't be able to)*

So I was already feeling frustrated, because I had better things planned this evening than trying to figure out how this works and API was returning `500` every time i tried to create application rule. - because #28 

Later I found out that rule types created by this process work **only for app stage `dev`**.

It was tedious and frustrating process that would not be possible without my `"insider"` position, so if I was newcomer to `Mergado platform` I might be pretty turned down by this (I am still frustrated, but I'll get over it quickly)

BTW  documentation on how to actualy create an instance of rule `type: "app"` is whole another issue.

**Conclusion (`TLDR`) : Creating application rule types suck. It's unusable for other than development purposes, sice you can't actualy create rule type that would work on production stage.**

**Comment by paveldedik** [comment]
I'm sorry we caused this frustration. We know that the process of creating new app rules is not properly thought through. BTW yes, you should be able to create multiple application rule types, even if it's not possible yet.

Hopefully the usability of creating new application rules will be improoved in the next iteration where we will focus on several things concerning the platform.

**Comment by michalwiglasz** [comment]
(A to jsem myslel, že jsem jediný zlý.)

**Comment by hudecsamuel** [comment]
I think I can close this rant 😄

**Comment by paveldedik** [comment]
lol

we heven't fixed it yet though :-D

**Comment by michalwiglasz** [comment]
re-o-pen, re-o-pen!

![image](https://media.rbl.ms/image?u=%2Ffiles%2F2016%2F06%2F03%2F636005686321411846-730249491_Carnival-Crowds.gif&ho=https%3A%2F%2Faz616578.vo.msecnd.net&s=594&h=c04ef33d4659db40e25d9639ac12292438156c4d747bdad7ba59194621b06fac&size=980x&c=1627022877)
