### ISSUE TITLE
Multi-user access and online auth

### ISSUE THREAD

**Issue by michalwiglasz** [mergado/mergado-apps#32]
Just curious:

- user 23 logins to Mergado and opens my app in export 789
- my app fetches online token with export id 789 and user id 23
- the token is stored in the database and reused until expires

after that:
- user 69 logins to Mergado and opens my app in export 789
- my app founds valid online token in the database and uses it
- but this token was generated for user 23 so it shouldn't be used for user 69, right?

What if user 69 has no access to export 789? How can I know which user is using my app without performing authentication every time?

**Comment by hudecsamuel** [comment]
> but this token was generated for user 23 so it shouldn't be used for user 69, right?

No it shouldn't.

> What if user 69 has no access to export 789? How can I know which user is using my app without performing authentication every time?

Well, you should do authentication for each individual user, that way you will be able to distingush if the curent user has access to export.

**Comment by michalwiglasz** [comment]
Soooo: How can I tell which user is currently using my app?

**Comment by hudecsamuel** [comment]
There is `"user_id"` in Access Token response ([docs](http://mergado.github.io/docs/api/authorization.html))
```json
{
    "access_token": "ras11",
    "expires_in": 3600,
    "token_type": "bearer",
    "entity_id": "5",
    "user_id": "1"
}
```

So you know which user is logged in in Mergado when you do the authorization request.

**Comment by michalwiglasz** [comment]
But I shouldn't do full authorization all the time? So if I have valid token stored in the DB, I want to use it, not re-auth every time.

**Comment by hudecsamuel** [comment]
Well how you decide to store the token is on you to implement. 
How are you dealing with authentication in your app?

At first i used session based authentication, with sessions that had oauth tokens assigned to them, now I am using [JWT](https://jwt.io/)

**Comment by michalwiglasz** [comment]
DB storage... not sure why I haven't though of sessions, this solves a lot of my issues...

**Comment by hudecsamuel** [comment]
Hope that will help.

Btw [mergado/logbook](https://github.com/mergado/logbook) is using sessions, even though it's not perfect it might give you some insight. Unfortunately I don't  have any documentation for it at this point.

**Comment by michalwiglasz** [comment]
.. and it uses some wierd framework I do not understand... :)

**Comment by hudecsamuel** [comment]
It's written using [Laravel framework](https://laravel.com/docs/5.2) , which is very well documented and maintained

 *`ehm ehm`*

**Comment by michalwiglasz** [comment]
I know ;)

![image](https://cloud.githubusercontent.com/assets/478122/20463984/04451c1e-af3f-11e6-8535-d829c6ca4fbd.png)

**Comment by michalwiglasz** [comment]
Conclusion: the docs should mention that too much persistent storage like database is not the right way and one should use sessions to store tokens. Otherwise... you know, what I wrote above can happen.
