### ISSUE TITLE
Apps have access to xenie-session cookie

### ISSUE THREAD

**Issue by michalwiglasz** [mergado/mergado-apps#34]
Any request to appcloud.mergado.com sends cookie `xenie-session` containing my session ID. Malicious app can hijack user sessions.

Caused by the fact that the session cookie has "wildcarded" domain (`domain=.mergado.com;` in `set-cookie` header). Difficult to avoid, though, because of the used subdomains (store, developers, ...)

**Comment by michalwiglasz** [comment]
Solution can be either fiddle with cookie settings (find out whether it is possible to whitelist different subdomains in `set-cookie` header) or move appcloud to different 2nd level domain.

**Comment by michalwiglasz** [comment]
And apps can see each others cookies if `path` is not set to `/apps/my-app-id`. Should be mentioned in docs.

**Comment by michalwiglasz** [comment]
This can also lead to conflicts, if two or more apps use same cookie name, i.e. `PHPSESSID`.

**Comment by hudecsamuel** [comment]
I was already wondering if this is possible, and sadly it is :cry:

**Comment by michalwiglasz** [comment]
Possible solution:
- buy newdomain.com
- add to DNS `*.newdomain.com CNAME appcloud.mergado.com`
- setup vhosts and routes etc. so each apps has its own subdomain, e.g. `myapp.dev.newdomain.com/apps/myapp.dev/eshop/12345` (keep /apps etc. so you don't break existing apps)

**Comment by smuuf** [comment]
The `iframe` in which the app is being rendered is **sandbox**ed and the sandbox is used with `allow-same-origin` attribute.

It is possible that the problem can be resolved by removing this attribute, but there needs to be a proper investigation about whether this wouldn't break anything else.

**Comment by michalwiglasz** [comment]
I guess this is not iframe related. Cookies are sent even if you open the page in separate tab. Not sure if `allow-same-origin` can fix this.

**Comment by michalwiglasz** [comment]
The xenie cookie is set for domain `*.mergado.com`, I haven't tested it, but I think that if you open page from `appcloud.mergado.com` it would be sent no matter what.

**Comment by smuuf** [comment]
The `allow-same-origin` attribute allows the browser to treat the contents of `iframe` as being-from-the-same-origin *even if* the `iframe` is **sandboxed**. Removing `allow-same-origin` attribute should tighten the `iframe`'s restriction policies and its contents would be treated as though it is from a different domain than the rest of the page (the *rest of the page* here being the Mergado around the `iframe`).

**Comment by michalwiglasz** [comment]
But the problem is that the content is NOT from different domain (both `.mergado.com`).

**Comment by michalwiglasz** [comment]
Would it really block access to cookies? My guess is that it blocks JS access to parent cookies, but the cookies are sent in HTTP header (actually they even have httpOnly flag, so JS has no access to it anyway)

**Comment by michalwiglasz** [comment]
Just tested it here: http://www.fit.vutbr.cz/~iwiglasz/cookie_stolen.html
Even if I check sandbox, the cookie is sent via http (as reported by chrome dev tools and wireshark).

**Comment by smuuf** [comment]
When I "enable sandbox" on your page I see the `HTML5 Sandbox blocked access to cookies.` text. Although I do see that Chrome sends the `Cookie:userid=example@tizen.org` header.

But is it possible that the `http://www.fit.vutbr.cz/~iwiglasz/iframe_cookie_stolen.html` page gets the cookie header not ***from the parent window***, but ***from itself***? Because in reality the cookie has already been set for the `iframe` context. It's been set by its parent, since the `iframe` is **first displayed without** the sandbox attribute.

**Comment by michalwiglasz** [comment]
Yes, it gets the cookie from itself, because it was sent over http. If I wrote some photos, I would be able to read the cookie even in sandboxed iframe.

Michal Wiglasz

1. 12. 2016 v 10:14, P?emysl Karbula <notifications@github.com<mailto:notifications@github.com>>:


When I "enable sandbox" on your page I see the HTML5 Sandbox blocked access to cookies. text. Although I do see that Chrome sends the Cookie:userid=example@tizen.org<mailto:userid=example@tizen.org> header.

But is it possible that the http://www.fit.vutbr.cz/~iwiglasz/iframe_cookie_stolen.html page gets the cookie header not from the parent window, but from itself? Because in reality the cookie has already been set for the iframe context. It's been set by its parent, since the iframe is first displayed without the sandbox attribute.

-

**Comment by michalwiglasz** [comment]
I guess I need to build some better example page ?

Michal Wiglasz

1. 12. 2016 v 10:14, P?emysl Karbula <notifications@github.com<mailto:notifications@github.com>>:


When I "enable sandbox" on your page I see the HTML5 Sandbox blocked access to cookies. text. Although I do see that Chrome sends the Cookie:userid=example@tizen.org<mailto:userid=example@tizen.org> header.

But is it possible that the http://www.fit.vutbr.cz/~iwiglasz/iframe_cookie_stolen.html page gets the cookie header not from the parent window, but from itself? Because in reality the cookie has already been set for the iframe context. It's been set by its parent, since the iframe is first displayed without the sandbox attribute.

-
