### ISSUE TITLE
API - rule data field content

### ISSUE THREAD

**Issue by hudecsamuel** [mergado/mergado-apps#36]
Hi I was figuring something out with Postman and Mergado API and when i was getting rules from a project I noticed there is some weird content of `"data" field in rule.

Endpoint: [List Project Rules](http://docs.mergado.apiary.io/#reference/core/rules/list-project-rules) (probably the same happens when trying to get single rule, but if that is the case it's probably same bug )

Field `"data"` should contain JSON object, instead it looks something like this:
```json
"data": "<mergado.model.rules.RuleApp object at 0x60ff950>"
```

It looks like it not serializing python model for that rule properly or something like that, and its happening on all types of rules I saw there so far.

**Comment by paveldedik** [comment]
Fixed in [0.3.1](http://mergado.github.io/docs/changelog/#mergado-apps-031)
