### ISSUE TITLE
Markdown in notification doesn't handle more than one link

### ISSUE THREAD

**Issue by hudecsamuel** [mergado/mergado-apps#37]
Adding markdown links to notification seems to work just fine with only one link:

```json
    "body": "**Data Owl**, [ ReglendoShop.com ](mergado://app/shops/3586/) : Zdá se, že zlobí propojení s Heurekou. Zkontrolujte prosím stav v aplikaci"
```
![screenshot from 2017-02-17 16 02 30](https://cloud.githubusercontent.com/assets/13395909/23070217/a5ffedbe-f52a-11e6-8af7-48c57a7843c5.png)

But when we added two it didn't parse it correctly and looked like this:
```json
    "body": "**Data Owl**, [ ReglendoShop.com ](mergado://app/shops/3586/) : Zdá se, že zlobí propojení s Heurekou. Zkontrolujte prosím stav v aplikaci [Keychain](mergado://app/shops/3586/keychain/)."
```
![screenshot from 2017-02-17 15 57 15](https://cloud.githubusercontent.com/assets/13395909/23070297/f34c1f16-f52a-11e6-9010-9166428616fe.png)

**Comment by SevoLukas** [comment]
Regexp lazy vs greedy loading in practice. Should be fixed in next release.
