### ISSUE TITLE
Mergado API - Logs

### ISSUE THREAD

**Issue by kajlus** [mergado/mergado-apps#38]
After calling URL
`https://app.mergado.com/api/projects/3586/logs/apply/` OR `https://app.mergado.com/api/projects/3586/logs/import/` OR `https://app.mergado.com/api/projects/3586/logs/export/`

Mergado API returns a JSON with `404 Not Found`
```
{"message": "The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again. You have requested this URI [/projects/3586/logs/apply/] but did you mean /projects/<id>/logs/apply/ or /projects/<id>/logs/import/ or /projects/<id>/logs/export/ ?"}
```

This is not a correct response, requested URL is identical with `did you mean` in response message.

**Comment by smuuf** [comment]
There indeed is *not* a project with this ID present. Where did you get it?

**Comment by kajlus** [comment]
Oh, well. We changed with `eshop_id` by mistake. Now it works, but the error message (if project does not exists) could be like `There is no project with ID $id`. Thanks :-)

**Comment by smuuf** [comment]
I guess that would be more appropriate response in this case. I agree. :)

**Comment by smuuf** [comment]
After consideration, we think this is an appropriate error response. The project did not exist, so `404` HTTP code was returned. Closing.
