### ISSUE TITLE
API - Rules - read_only attribute

### ISSUE THREAD

**Issue by hudecsamuel** [mergado/mergado-apps#4]
When application is creating a rule there is only ``deletable`` option to restrict user interaction with that rule in GUI. It would probably be nice to have rule with wich the user can not directly interact (changing them, changing their priority).
I suggest some attribute to allow this in through API.

**Comment by paveldedik** [comment]
This will be resolved in the next release (0.1.2).

**Comment by paveldedik** [comment]
This has been resolved, see the [Change Log](http://mergado.github.io/docs/changelog/).
