### ISSUE TITLE
Statistics- heureka_min_cpc is null

### ISSUE THREAD

**Issue by hudecsamuel** [mergado/mergado-apps#41]
For the past few days we encountered more projects where API returned statistics of (almost) all products with the attribute `heureka_min_cpc` as `null`. 

This is a problem since we not only use this in calculations, but we also check if statistics have all the data we need or we should just ignore them.

[Enpoint](http://docs.mergado.apiary.io/#reference/statistics/product-statistics/statistics-of-all-products) (also others for statistics of products)

**Comment by paveldedik** [comment]
There was a problem with one of our modules which scrapes and updates prices of minimal CPCs from Heureka. It should be fixed now.
