### ISSUE TITLE
Informations about errors during rule application

### ISSUE THREAD

**Issue by hudecsamuel** [mergado/mergado-apps#45]
There are multiple cases that application rule can result in error in mergado without actualy have any exception, and then it's hard to find the problem, sometimes even find that there is a problem, since there is no information which rule caused it. Currently a developer only sees the number of errors during rule application.

![screenshot from 2017-07-10 14-47-14](https://user-images.githubusercontent.com/13395909/28018753-c5f2d400-657e-11e7-8080-de939c70c938.png)

It would help if there was a bit more information about the errors (we don't need your stacktrace or anything like that, but having more information would be helpful for us . For example in which rule the error occured, was there a timeout, status code > 400, invalid data).

**Comment by paveldedik** [comment]
This has been implemented in version 0.3.16
