### ISSUE TITLE
Shared sessionStorage and LocalStorage

### ISSUE THREAD

**Issue by hudecsamuel** [mergado/mergado-apps#47]
All apps have shared `localStorage` and `sessionStorage`. This can cause that apps unwillingly 
 (or on purpose) reads/rewrites/deletes entries by other apps to this kind of storage, since it's not possible to scope it to specific path like cookies (it's scoped by origin)[[1](https://stackoverflow.com/questions/25013643/is-it-possible-to-use-localstorage-with-context-per-path-like-cookie)][[2](https://www.w3.org/TR/webstorage/#the-localstorage-attribute)].

The only solution seems to have apps on different origins, which as far as I know is not currently possible.

**Comment by smuuf** [comment]
Considering there are other problems with having apps sharing the same origin than this, we *are* considering moving Appcloud to a different, standalone domain.

It wouldn't be so simple and there are many potential problems that would have to be considered. One of them being:

> *To what degree are developers - in their codebase - counting on Appcloud having some specific (current) base URL?* What could go wrong in their applications if their base URL would just change?

This question is not about setting developers' SSH configurations and whatnot, but the actual apps' logic. *Routing that would have to be - maybe - modified*, and stuff like that. How much in advance should we announce such change to app developers?

**Comment by hudecsamuel** [comment]
> How much in advance should we announce such change to app developers?

Speaking for Reglendo: I say a week or two. We use base url in some constants (such as oauth2 redirect url), but we keep them in top level environment files so this wouldn't be difficult to change.
