### ISSUE TITLE
API- Creating element with white-space and special characters

### ISSUE THREAD

**Issue by hudecsamuel** [mergado/mergado-apps#53]
Creating Element with whitespace will result in `500 Internal Server Error`:

![screenshot from 2017-08-02 10-04-59](https://user-images.githubusercontent.com/13395909/28863973-498ea5e8-776b-11e7-9516-052156e98c8e.png)

The same applies for diacritic:

![screenshot from 2017-08-02 10-01-06](https://user-images.githubusercontent.com/13395909/28863978-4c92bbe4-776b-11e7-84fc-a452696d86df.png)

There should probably be some server side validation and return more specific status code (like `400`)

**Comment by MichalJanik** [comment]
What is the status @smuuf ?

**Comment by smuuf** [comment]
Now in backlog.

**Comment by paveldedik** [comment]
This issue has been resolved in 0.3.12
