### ISSUE TITLE
/eshop/info - stats_collection - missing date

### ISSUE THREAD

**Issue by kluvi** [mergado/mergado-apps#54]
missing date, to which the stats_collection relates to...

example:
20.11. 01:00 - stats_collection.status = done, but stats for 19.11. are not ready, status "done" is for 18.11.

**Comment by MichalJanik** [comment]
What is the status?
Need more information @smuuf ?

**Comment by smuuf** [comment]
What are our options here, @paveldedik?

**Comment by paveldedik** [comment]
As @kluvi suggests, adding a field `stats_collection.date` would resolve this issue. However, the field `stats_collection.started_at` can be used to determine the `date`, so this is just more convenient way of returning the information.

**Comment by smuuf** [comment]
This has been resolved by adding logs of stats gathering to our API. Docs here: https://mergado.docs.apiary.io/#reference/statistics/logs-of-the-import-of-statistics/list-all-logs-of-a-shop
