### ISSUE TITLE
/logs/apply - add more data

### ISSUE THREAD

**Issue by kluvi** [mergado/mergado-apps#55]
- task_id
- type: apply on all products / synchronization
- who adds the task to apply - user / app (and which app) / mergado
- details like in UI - list of processed rules with products / errors count for each rule
- error details (like in UI)

**Comment by paveldedik** [comment]
What do you mean by the `type`? Synchronization (import) and export have different endpoints. And we won't add the `task_id` field as tasks are deprecated.
