### ISSUE TITLE
API - Rules - rules without queries

### ISSUE THREAD

**Issue by hudecsamuel** [mergado/mergado-apps#6]
When rule is created through API, it defaults to no query (This behaves as if there were no pproducts selected for that rule). Only subsequently we can add queries to this rule, even the default query named ``♥ALLPRODUCTS♥``.
 My proposal is that rules with no queries assigned defaults to all products even without this query.

**Comment by paveldedik** [comment]
I believe this is how the API behaves now (it was implemented some time ago). Thanks for the proposal!
