### ISSUE TITLE
/logs/appy - time not in UTC

### ISSUE THREAD

**Issue by kluvi** [mergado/mergado-apps#64]
It looks, that started_at and finished_at in apply log is not in UTC.

**Comment by MichalJanik** [comment]
What is the status?
Need more information @smuuf ?

**Comment by smuuf** [comment]
This has been fixed in **Mergado Apps 0.3.11**. Closing.

More info about *0.3.11* release: https://forum.mergado.cz/t/novinky-v-platforme-pro-vyvojare/318/15

**Comment by smuuf** [comment]
Seem like there's still an issue with these. Reopening.

**Comment by smuuf** [comment]
The fix went straight to production today as a part of "release garbage" fixes.

Closing.
