### ISSUE TITLE
stats - heureka_is_paired is sometimes null

### ISSUE THREAD

**Issue by kluvi** [mergado/mergado-apps#67]
It should be true or false. I think, that there is no "maybe" state :)

**Comment by smuuf** [comment]
Thank you for the report. Looks like either *a tip for enhancement* or *a bug*.

**Comment by MichalJanik** [comment]
What is the status @smuuf ?

**Comment by paveldedik** [comment]
Unfortunately, `null` means, that _we don't know_, there is not enough data.

**Comment by smuuf** [comment]
Is there something we can do better about that, @paveldedik?

**Comment by paveldedik** [comment]
We can scrape heureka for example. `null` values would still be possible in some cases though.
