### ISSUE TITLE
upgrade MySQL to newer version

### ISSUE THREAD

**Issue by kluvi** [mergado/mergado-apps#68]
This is **a feature request**

---

### Expected behaviour
Newer version of MySQL (MariaDB) - at least 5.6
5.6 allows to perform alter table without locking tables - see https://stackoverflow.com/a/35426301

### Actual behaviour
There is only MariaDB 5.5

**Comment by smuuf** [comment]
Appcloud naw has MariaDB version 10: `5.5.5-10.2.10-MariaDB-log`

Have fun. :)
