### ISSUE TITLE
App rules cleaning

### ISSUE THREAD

**Issue by kluvi** [mergado/mergado-apps#69]
This is **a bug report**

---

### Expected behaviour
Delete all app rules from Mergado after disabling app.

### Actual behaviour
When user disables app and hook app.disable failed for some reason (error,...), then in Mergado can stuck some app rules. These app rules cant be deleted by developer/app, because app cant authenticate in API. If there is some stuck rules, Mergado sends rule-requests to app.

#### More details
projects 17178, 22146, 13923

**Comment by smuuf** [comment]
I think this is more of a feature request.

When we designed the behaviour of our platform in regards to *what to do* when user disables *the app*, we talked about whether we *(as Mergado)* should do some sort of cleanup afterwards.

It was decided that *"no, the app should clean up after itself"*. Which *(even personally)* I still think is a pretty good strategy.

Mergado can't possibly know about everything it should clean, revert or how to undo everything some app might have done. And even if it did, it might be the best thing to do *(think of some app that does some one-time feed optimization, or whatever)*.

*(Ok, that was some background - for context.)*

That being said, deleting app's own rules - after the app is disabled - ***sounds pretty reasonable to me*** *(if done right - this has to be thought through)*.
