### ISSUE TITLE
Developers - releases sorting

### ISSUE THREAD

**Issue by kluvi** [mergado/mergado-apps#70]
This is **a bug report**

---

### Actual behaviour
![screenshot_20171122_150708](https://user-images.githubusercontent.com/234987/33131475-ecd05818-cf96-11e7-9769-fdc82d6f8e34.png)
![screenshot_20171122_150725](https://user-images.githubusercontent.com/234987/33131477-ed0b3988-cf96-11e7-97e0-215002cad93e.png)

**Comment by smuuf** [comment]
Sorting looks pretty messed up.
