### ISSUE TITLE
API - příznak zda je povoleno "Generovat XML reporty"

### ISSUE THREAD

**Issue by jrkgnk** [mergado/mergado-apps#73]
This is **a feature request**

---

### Expected behaviour
Přidat do API info o tom, zda má e-shop povoleno generování statistických XML z Heureky. Bez toho není v API Heureka URL.
// Heureka URL je i v Sortiment reportu

Díky

![mereni-konverzi](https://user-images.githubusercontent.com/17846924/33271027-56772eca-d386-11e7-9527-1a0724810a5d.png)

**Comment by MichalJanik** [comment]
Nebylo toto ošetřeno v rámci toho, jak Peter dělal ten balík scrapování? Není to tedy na backendu hotové a stačí pouze "vytáhnout" někam ven?

**Comment by smuuf** [comment]
Ping @paveldedik, co říkáš?

**Comment by paveldedik** [comment]
See the docs - https://mergado.docs.apiary.io/#reference/statistics/eshop-statistics

> **heureka_generate_xml_reports** (*boolean*) - Whether eshop administrator enabled to generate XML reports with measurements of conversions on Heureka.

**Comment by MichalJanik** [comment]
Ping @jrkgnk
