### ISSUE TITLE
Appcloud - wkhtmltopdf

### ISSUE THREAD

**Issue by martinhrncir** [mergado/mergado-apps#74]
This is **a feature request**
---
### Expected behaviour
Working whktmltopdf on appcloud

### Actual behaviour
No whktmltopdf on appcloud

#### More details 
Please please install [wkhtmltopdf](https://wkhtmltopdf.org/) to [appcloud.mergado.com](appcloud.mergado.com)

**Comment by MichalJanik** [comment]
@smuuf jak toto vidíš prosím časově? Kdy se k tomu dostaneš?
Děkuji.

**Comment by smuuf** [comment]
Když to dobře půjde, tak by to tam dnes už snad mohlo být.

**Comment by MichalJanik** [comment]
Super.
Děkuji
a těším se :smile: .

**Comment by smuuf** [comment]
Ok, from now on `wkhtmltopdf` is available on Appcloud.

## Example usage
`$ htmltopdf www.google.com output.pdf`

*Note: `htmltopdf` is a helper script wrapper around `wkhtmltopdf`.*

**Comment by MichalJanik** [comment]
Ping @martinhrncir

**Comment by martinhrncir** [comment]
vim o tom, otestovano, funguje, dik :+1:
