### ISSUE TITLE
MAIA - ScrollTo method is working weirdly

### ISSUE THREAD

**Issue by martinhrncir** [mergado/mergado-apps#76]
This is **a bug report**

---

### Expected behaviour
App calls scrollTo(200), iframe scrolls to 200px. Then app calls scrollTo(0) and iframe scrolls to top

### Actual behaviour
App calls scrollTo(200), iframe scrolls to 200px. Then app calls scrollTo(0) and iframe stills at position.

#### More details
For more details please feel free to visit us in our office.

**Comment by MichalJanik** [comment]
What is the status @rajmundHutar ?

**Comment by rajmundHutar** [comment]
It's fixed, will be in next release.

**Comment by MichalJanik** [comment]
Thanks.

**Comment by smuuf** [comment]
Is released. Closing.
