### ISSUE TITLE
stats - missing heureka_url,...

### ISSUE THREAD

**Issue by kluvi** [mergado/mergado-apps#77]
This is **a bug report**

---

### Expected behaviour
Return heureka_url if eshop has sortiment_feed, but not conversion_feed. There is also more fields, that are in both sortiment_feed and conversion_feed

### Actual behaviour
Missing heureka_url,...

#### More details 
Some eshops doesnt have conversion_feed, but has sortiment_feed. It is impossible to get heureka_url in this case, which is necessary for some kind of apps.

**Comment by MichalJanik** [comment]
What is the status?
Need more information @smuuf ?

**Comment by smuuf** [comment]
Status is that *we do have this in our internal backlog*, but our backend guys are currently swamped with other stuff.

**Comment by MichalJanik** [comment]
Swamped?
Like this?
![business1](https://user-images.githubusercontent.com/608857/33940966-57f13fce-e011-11e7-9577-12a7e11489a4.jpg)
(Source: https://cdn77.eatliver.com/wp-content/uploads/2016/08/business1.jpg )

Is it possible to solve it in this iteration?

**Comment by smuuf** [comment]
This issue is currently planned in our roadmap for February. *(Ie. iteration starting from Wednesday, 10/01/2018 onwards)*.

**Comment by smuuf** [comment]
This has been on production since January. Closing.
