### ISSUE TITLE
Store - Náhledový obrázek og:image

### ISSUE THREAD

**Issue by jrkgnk** [mergado/mergado-apps#78]
This is **a feature request**

---

### Expected behaviour
Obrázek by měl mít poměr stran 1.91:1, aby se jej Facebook korektně zobrazil. 

### Actual behaviour
Nyní se používá čtvercový a FB pak udělá ořez.

#### More details 
Nástroj pro testování zde https://developers.facebook.com

  
> Use images that are at least 1200 x 630 pixels for the best display on high resolution devices. 
> At the minimum, you should use images that are 600 x 315 pixels to display link page posts with larger images. Images can be up to 8MB in size.

https://developers.facebook.com/docs/sharing/best-practices/
![facebook-nahled](https://user-images.githubusercontent.com/17846924/34771716-defe17e4-f605-11e7-9e67-d819ee6d7bab.png)

**Comment by smuuf** [comment]
Scheduled for release in the following maintenance update next Wednesday, *24th Janurary 2018*.

**Comment by smuuf** [comment]
Released yesterday. Closing.
