### ISSUE TITLE
 Statistics of a Product nevrací všechna data

### ISSUE THREAD

**Issue by jrkgnk** [mergado/mergado-apps#79]
This is **a bug report**
---

### Actual behaviour
API vrací u produktu jen část dat ze statistik. Jeden den je to v pohodě a druhý den jen část dat. Někdy chybí ceny, další den ceny jsou, ale není HEUREKA_URL...
## Neúplná data
https://app.mergado.com/api/products/261493601/stats/?date=2018-01-12
```
{
   "date": "data_data",
   "product_id": "data_data",
   "stats": {
       "name": "data_data",
       "url": "data_data",
       "categorytext": "data_data",
       "price": null,
       "delivery_date": 0,
       "imgurl": "data_data",
       "heureka_cpc": 4.57,
       "item_id": "data_data",
       "price_vat": 64,
       "manufacturer": "data_data",
       "is_topseller": false,
       "cost": 53.47,
       "is_starter": false
    }
}
```
https://app.mergado.com/api/products/261493601/stats/?date=2018-01-13
```
{
    "date": "data_data",
    "product_id": "data_data",
    "stats": {
        "name": "data_data",
        "url": "data_data",
        "categorytext": "data_data",
        "price": null,
        "delivery_date": 0,
        "imgurl": "data_data",
        "heureka_cpc": null,
        "item_id": "data_data",
        "price_vat": 64,
        "manufacturer": "data_data"
    }
}
```
https://app.mergado.com/api/products/261493601/stats/?date=2018-01-15
```
{
    "date": "data_data",
    "product_id": "data_data",
    "stats": {
        "name": "data_data",
        "url": "data_data",
        "categorytext": "data_data",
        "price": null,
        "delivery_date": 0,
        "imgurl": "data_data",
        "heureka_cpc": 7.75,
        "item_id": "data_data",
        "price_vat": 64,
        "manufacturer": "data_data",
        "heureka_max_prices": [
            146,
            126,
            110,
            107,
            105,
            104,
            102,
            101,
            100,
            100
        ],
        "heureka_min_prices": [
            54,
            54,
            55,
            55,
            55,
            56,
            59,
            59,
            59,
            64
        ],
        "heureka_segment": null,
        "heureka_price_position": 10,
        "heureka_category": "data_data",
        "heureka_shops_count": 73,
        "heureka_popularity": 98,
        "is_topseller": false,
        "cost": 53.47,
        "is_starter": false
    }
}
```

**Comment by paveldedik** [comment]
Jsou tam neúplná data, protože pro 2018-01-12 a 2018-01-13 nebyly staženy všechny statistiky. To kvůli tomu, že je Heureka nevygenerovala.

Jaké je optimální řešení tohoto problému? Stačí přidat historii stahování statistik do API (zpřístupnit historii chyb které při stahování nastaly)? Nebo jak jinak to řešit?

@jrkgnk

**Comment by kluvi** [comment]
Ta historie stahování statistik sice nevyřeší problém, ale aspoň půjde poznat v čem je problém a dost nám to pomůže s diagnostikou problému. Určitě bych tam nechal i informaci o úspěšném stažení (tj kdy se statistiky reálně stáhly). Tím by se zároveň vyřešilo i https://github.com/mergado/mergado-apps/issues/54

**Comment by smuuf** [comment]
This has been resolved by adding logs of stats gathering to our API. Docs here: https://mergado.docs.apiary.io/#reference/statistics/logs-of-the-import-of-statistics/list-all-logs-of-a-shop
