### ISSUE TITLE
OAuth2 - RefreshTokenGrant - resource_owner_id

### ISSUE THREAD

**Issue by hudecsamuel** [mergado/mergado-apps#8]
Access token from ``refresh_token`` grant doesn't return ``resource_owner_id``.
The logic is already implemented in ``authorization_code`` grant, but somebody forgot to do it in refresh_token grant (me :smile: )

![screenshot from 2016-04-12 14 43 44](https://cloud.githubusercontent.com/assets/13395909/14485692/dd0f8bc8-0158-11e6-8218-4505f17486b8.png)

This doesn't break anything or something like that, it would just be nice to have it consistent with accesstoken from authorization code grant.

**Comment by smuuf** [comment]
In the new, reworked OAuth server the *access token* coming from "*refresh token*" (or *Mergado Refresh Token* as we like to call it now) will represent an *offline* access to entities that have your application enabled - and thus **such access token won't be linked to any user** (or *resource owner*) at all.

Issue is therefore unsubstantiated from now on. You (the apps' developers) simply won't need it :)
