### ISSUE TITLE
Čas v applylogs není UTC, ale UTC +1

### ISSUE THREAD

**Issue by jrkgnk** [mergado/mergado-apps#80]
This is **a bug report**
---

### Actual behaviour
Stejný problém jako zde #64 

V API se vrací čas např. `2018-01-18T11:48:57+00:00` a přímo v rozhraní je stejný čas `18. 01. 2018, 11:48:57`. 

Buď je v API špatně čas označen, nebo se v rozhraní nezobrazuje čas pro Europe/Prague.

**Comment by smuuf** [comment]
Actually a duplicate of #64. Reopening that one and closing this one as duplicate.
