### ISSUE TITLE
Developers - Server Error

### ISSUE THREAD

**Issue by jrkgnk** [mergado/mergado-apps#87]
Poměrně často se stává, že v developers je vidět server error viz obrázek ze stránky Přehled (konkrétní aplikace). 

![app mergado com-2018 05 02-08-47-37](https://user-images.githubusercontent.com/17846924/39509200-a879346e-4de5-11e8-9d2f-fa0d14176dd0.png)

**Comment by smuuf** [comment]
This is caused by our backend servers not responding in time, sometimes. We *are* looking into this.
