### ISSUE TITLE
OAuth2 - RefreshTokenGrant - token refresh for user without permission

### ISSUE THREAD

**Issue by hudecsamuel** [mergado/mergado-apps#9]
I'm not sure if this should work like this but now RefreshToken grant is working even after the user  had their permissions removed from entity. This is due to the fact that it doesn't check users premissions there, just if the token is valid.
The ideal result would be 401/403 Unauthorized (or 400?) error on such request. Another solution would be to remove users refresh token after permission removal (I think AccessToken is already removed).
 Currently the token is refreshed, returning new Refresh and AccessToken, but requests to API result in 403.

**Comment by smuuf** [comment]
This issue is now unsubstantiated as well. See https://github.com/mergado/mergado-apps/issues/8#issuecomment-224586440
