### ISSUE TITLE
Úprava názvu aplikace

### ISSUE THREAD

**Issue by jrkgnk** [mergado/mergado-apps#90]
This is **a feature request**

---
V Developers nelze aktuálně měnit název aplikace. 
Hodilo by se nám to +  přesměrovat URL (301)  adresy co vedou na Store na novou adresu. 

## příklad
Starý název - Super App -> url do Store je https://store.mergado.com/detail/superapp
Nový název - Mega App -> url https://store.mergado.com/detail/megaapp

Přesměrování

` https://store.mergado.com/detail/superapp` --> (301) --> `https://store.mergado.com/detail/megaapp`

**Comment by paveldedik** [comment]
Probrali jsme to a nemyslíme si, že to přesměrování je dobrý nápad. Když si změníš uživatelské jméno na githubu, přesměrování taky nedostaneš.

Blbý je hlavně to, že pokud změníš jméno aplikace, blokuješ starou URL, čehož třeba může zneužít konkurence.

Je to samozřejmě stále k diskuzi, jen píšu pro info.

**Comment by jrkgnk** [comment]
Když změníš název produktu na e-shopu, tak je přesměrování velmi žádané...
To, že se při změně uživatelského jména nepřesměrovává a zruší mi přijde také zneužitelné a ještě více. Na vybudovaném jménu se dá podvod lépe stavět.

Nicméně je asi trochu rozdíl mezi uživatelským účtem a názvem produktu.

**Comment by paveldedik** [comment]
Tak to je potom důvod nepovolit změnu vůbec.

A mimochodem pro zajímavost, na Google Play taky není možné změnit url adresu aplikace, viz https://stackoverflow.com/questions/17582289/is-it-possible-to-change-the-package-name-of-an-android-app-on-google-play
