### ISSUE TITLE
Staging verze aplikace

### ISSUE THREAD

**Issue by jrkgnk** [mergado/mergado-apps#91]
This is **a feature request**

Přidat staging verze aplikace. Dev verze aplikace napojená na produkční databázi.

**Comment by smuuf** [comment]
Nevidím rozumný důvod, proč toto zavádět jako součást platformy. Proč by - reálně - dev verze aplikace měla *vůbec někdy* používat produkční databázi? To je nebezpečná věc.

Pokud takové harakiri chtějí vývojáři dělat, stále mají možnost si takovou věc zařídit sami - ať už v dev verzi aplikace - ze které se mohou napojit na produkční databázi (což je dosti nebezpečné), tak i v produkční verzi, kde mohou mít na některém místě, (např.) u konkrétního exportu, vypodmínkovanou nějakou novou funkcionalitu, pokud ji potřebují testovat na reálných datech (také nebezpečné).
