### ISSUE TITLE
Počet pokusů při aplikaci pravidel

### ISSUE THREAD

**Issue by kluvi** [mergado/mergado-apps#93]
This is **a feature request**

---

### Expected behaviour
Někam do requestů (hlavičky / tělo) co posílá Mergado aplikaci při aplikaci pravidel bych potřeboval doplnit:
- timeout, který Mergado použije pro daný request
- počet pokusů, kolikrát se snaží request zopakovat v případě chyby
- kolikáty pokus ten daný request aktuálně je

Cílem je mít možnost na straně aplikace vytvořit takové řešení, aby nedocházelo zbytečně k přerušování aplikace pravidel v Mergadu pokud je chyba na straně aplikace. Aplikace může při posledním pokusu vrátit například prázdná data nebo nějaká nacachovaná,...

**Comment by paveldedik** [comment]
* `timeout` poslat můžu, pokud ho budeme mít nastavený, ten ale nastavený aktuálně není, takže timeoutuje apache na app cloudu. Takže můžu to tam přidat, ale budu posílat `null`, protože nemám šanci vědět, jaký je nastavený timeout, když hosting už teoreticky nemusí být ani app cloud. Timeout je zrušený kvůli usekávání requestů, tedy chybě v httplib. Zatím nás nenapadlo efektivní řešení, jak tam ten timeout zase vrátit. Navíc pokud je na serveru nastavený menší timeout, než na backendu Mergada, nebude ta informace moc užitečná.
* celkový počet pokusů poslat můžu, to není problém
* kolikátý pokus daný request je poslat bohužel nemůžu (nejspíš to nějak jde, jen si nejsem jist, jestli to stojí za tu práci a jak velký je to hacking), používáme sessions z knihovny request a ta za nás volá `retry` stejného requestu sama, posílá se tedy úplně stejný request znovu (kopie), nemůžu tedy v body upravit nějaký field, ani upravit headers. To však znamená, že se v requestu posílá i stejné `request_id`, které si u sebe můžete počítat a podle toho určit, kolikátý pokus ten request je.

Co myslíš @kluvi ? Jediná opravdu přidaná hodnota by byl ten celkový počet pokusů, který je teď staticky definovaný jako `5`.

**Comment by kluvi** [comment]
Pokud se to opravdu nebude jen tak měnit, tak prosím přidejte všechny 4 informace (timeout mergada, timeout(y) appcloudu, počet pokusů mergada, informace o request_id) do dokumentace, ať je to zřejmé že/jak to má být (a vývojáři tak mají alibi když se něco pokazí).

Timeout - problém nastane v případě, že by byl timeout mergada menší než timeout hostingu, to pak nemá šanci aplikace ovlivnit. Ona to nemůže ovlivnit ani v případě hostingu na appcloudu, ale bylo by fajn si toto jasně nadefinovat jak to je. Pokud bude aplikace hostovaná mimo appcloud, je to pochopitelně její zodpovědnost.

Jinak souhlasím, s těmito informace by mělo být možné dosáhnout požadovaného cíle za předpokladu, že se ty čísla nebudou měnit (nebo se to zavčas oznámí předem).

**Comment by paveldedik** [comment]
Přidal jsem něco do dokumentace: http://mergado.github.io/docs/apps/rules-and-queries.html#retrying-on-errors

Jinak toto bohužel zatím implementovat nebudeme z důvodů viz můj předchozí komentář.
