### ISSUE TITLE
No client id supplied po přihlášení do aplikace

### ISSUE THREAD

**Issue by jrkgnk** [mergado/mergado-apps#95]
Po přihlášení do aplikace se občas objeví jen
```
{
"error": "invalid_client",
"error_description": "No client id supplied"
}
```

**Comment by smuuf** [comment]
Do jaké aplikace? Do Mergada, nebo do vaší aplikace? Kde přesně se to objeví? A dá se "občas" specifikovat více?

**Comment by jrkgnk** [comment]
V místě iframe pro aplikaci.

Bohužel se to nedá lépe specifikovat. Naposledy v okamžik, kdy jsem zakládal tuto issue.

![screenshot_20180910_103551](https://user-images.githubusercontent.com/17846924/45950029-4e3cb580-bffe-11e8-97b7-2ee81022bc13.png)
