### ISSUE TITLE
Chybí náklady u statistik ze Zboží.cz

### ISSUE THREAD

**Issue by martinhrncir** [mergado/mergado-apps#96]
This is **a bug report**

---

V endpointu produktových statistik u Zboží.cz chybí položky s náklady.

### Actual behaviour
URL: https://api.mergado.com/projects/334/stats/products/?limit=1000&date=2018-09-20

U produktů úplně chybí položky zbozi_conversion_cost_czk* i u těch, které mají nějaký proklik a tedy by měly mít i náklad. Např konkrétně produkt product_id: "2851577" ve dne 2018-09-20, viz URL výše

**Comment by paveldedik** [comment]
Ve staženém CSV reportu ze zboží jsou všechna `zbozi_conversion_cost_czk*` nulová u tohoto eshopu.

Můžu poslat CSV report, podle kterého si to můžeš ověřit.

**Comment by martinhrncir** [comment]
Oka, chyba u nás, zamotali jsme se v pojmenování sloupců, můžem zavřít. dik.
