### ISSUE TITLE
API - Celkový počet záznamů

### ISSUE THREAD

**Issue by kluvi** [mergado/mergado-apps#97]
This is **a feature request**

---

### Expected behaviour
Následující endpointy by mohly v odpovědi vracet celkový počet záznamů pro daný request (bez ohledu na limit/offset)

- `/projects/id/stats/products`
- `/shops/id/stats/products`
- `/shops/id/google/analytics`
- `/projects/id/google/analytics`

V odpovědi by mohlo být něco jako
```
{
  "data": [
   ...
  ],
  "limit": 10,
  "offset": 0,
  "total": 123456
}
```

### Actual behaviour
U některých endpointů lze získat hodnoty oklikou (přes `/shops/id/statslogs`) a u některých (google analytics) je aktuálně nelze získat nijak.

**Comment by ondrejbenes** [comment]
Implementováno v API verzi 2.0.1
https://forum.mergado.cz/t/novinky-v-platforme-pro-vyvojare/318/25
